import Header from '../components/Header'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <header
          style={{backgroundColor : "lightblue",padding : "1rem"}}
        >
          <p>Header</p>
        </header> */}
        <Header />
        {children}
        {/* <footer 
          style={{backgroundColor : "gray",padding:"1rem"}}
        >
          <p>Footer</p>
        </footer> */}
        <Footer/>
      </body>
    </html>
  )
}
